# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\addUsers.ui'
#
# Created: Fri Apr 14 17:34:41 2017
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Users(object):
    def setupUi(self, Users):
        Users.setObjectName(_fromUtf8("Users"))
        Users.setWindowModality(QtCore.Qt.ApplicationModal)
        Users.resize(800, 351)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/add-user.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Users.setWindowIcon(icon)
        Users.setLayoutDirection(QtCore.Qt.RightToLeft)
        Users.setStyleSheet(_fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(Users)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 781, 201))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.textEmail = QtGui.QLineEdit(self.groupBox)
        self.textEmail.setGeometry(QtCore.QRect(510, 109, 261, 31))
        self.textEmail.setMaxLength(50)
        self.textEmail.setObjectName(_fromUtf8("textEmail"))
        self.textNumberID = QtGui.QLineEdit(self.groupBox)
        self.textNumberID.setGeometry(QtCore.QRect(240, 29, 261, 31))
        self.textNumberID.setMaxLength(20)
        self.textNumberID.setObjectName(_fromUtf8("textNumberID"))
        self.textFullName = QtGui.QLineEdit(self.groupBox)
        self.textFullName.setGeometry(QtCore.QRect(510, 29, 261, 31))
        self.textFullName.setMaxLength(50)
        self.textFullName.setObjectName(_fromUtf8("textFullName"))
        self.textUsername = QtGui.QLineEdit(self.groupBox)
        self.textUsername.setGeometry(QtCore.QRect(510, 69, 261, 31))
        self.textUsername.setMaxLength(20)
        self.textUsername.setObjectName(_fromUtf8("textUsername"))
        self.textNumberPhone = QtGui.QLineEdit(self.groupBox)
        self.textNumberPhone.setGeometry(QtCore.QRect(240, 70, 261, 31))
        self.textNumberPhone.setMaxLength(15)
        self.textNumberPhone.setObjectName(_fromUtf8("textNumberPhone"))
        self.textPassword = QtGui.QLineEdit(self.groupBox)
        self.textPassword.setGeometry(QtCore.QRect(510, 150, 261, 31))
        self.textPassword.setMaxLength(50)
        self.textPassword.setObjectName(_fromUtf8("textPassword"))
        self.labAddImgUser = QtGui.QLabel(self.groupBox)
        self.labAddImgUser.setGeometry(QtCore.QRect(10, 30, 211, 151))
        self.labAddImgUser.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.labAddImgUser.setText(_fromUtf8(""))
        self.labAddImgUser.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/users.png")))
        self.labAddImgUser.setScaledContents(True)
        self.labAddImgUser.setObjectName(_fromUtf8("labAddImgUser"))
        self.labShowPassword = QtGui.QLabel(self.groupBox)
        self.labShowPassword.setGeometry(QtCore.QRect(470, 150, 31, 31))
        self.labShowPassword.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.labShowPassword.setText(_fromUtf8(""))
        self.labShowPassword.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/eyePassword.png")))
        self.labShowPassword.setScaledContents(True)
        self.labShowPassword.setObjectName(_fromUtf8("labShowPassword"))
        self.comboxSex = QtGui.QComboBox(self.groupBox)
        self.comboxSex.setGeometry(QtCore.QRect(240, 110, 261, 31))
        self.comboxSex.setObjectName(_fromUtf8("comboxSex"))
        self.comboxSex.addItem(_fromUtf8(""))
        self.comboxSex.addItem(_fromUtf8(""))
        self.comboxSex.addItem(_fromUtf8(""))
        self.labCreatePasswordComplix = QtGui.QLabel(self.groupBox)
        self.labCreatePasswordComplix.setGeometry(QtCore.QRect(410, 150, 31, 31))
        self.labCreatePasswordComplix.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.labCreatePasswordComplix.setText(_fromUtf8(""))
        self.labCreatePasswordComplix.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/createPassword.png")))
        self.labCreatePasswordComplix.setScaledContents(True)
        self.labCreatePasswordComplix.setObjectName(_fromUtf8("labCreatePasswordComplix"))
        self.textCreatePasswordComplix = QtGui.QLineEdit(self.groupBox)
        self.textCreatePasswordComplix.setGeometry(QtCore.QRect(240, 150, 141, 31))
        self.textCreatePasswordComplix.setMaxLength(20)
        self.textCreatePasswordComplix.setReadOnly(True)
        self.textCreatePasswordComplix.setPlaceholderText(_fromUtf8(""))
        self.textCreatePasswordComplix.setObjectName(_fromUtf8("textCreatePasswordComplix"))
        self.textPasswordShow = QtGui.QLineEdit(self.groupBox)
        self.textPasswordShow.setGeometry(QtCore.QRect(510, 150, 261, 31))
        self.textPasswordShow.setMaxLength(50)
        self.textPasswordShow.setObjectName(_fromUtf8("textPasswordShow"))
        self.groupBokPer = QtGui.QGroupBox(Users)
        self.groupBokPer.setGeometry(QtCore.QRect(10, 228, 781, 41))
        self.groupBokPer.setObjectName(_fromUtf8("groupBokPer"))
        self.checkBoxGen = QtGui.QCheckBox(self.groupBokPer)
        self.checkBoxGen.setGeometry(QtCore.QRect(682, 80, 81, 31))
        self.checkBoxGen.setObjectName(_fromUtf8("checkBoxGen"))
        self.checkBoxCalc = QtGui.QCheckBox(self.groupBokPer)
        self.checkBoxCalc.setGeometry(QtCore.QRect(535, 80, 111, 31))
        self.checkBoxCalc.setObjectName(_fromUtf8("checkBoxCalc"))
        self.checkBoxChat = QtGui.QCheckBox(self.groupBokPer)
        self.checkBoxChat.setGeometry(QtCore.QRect(420, 80, 81, 31))
        self.checkBoxChat.setObjectName(_fromUtf8("checkBoxChat"))
        self.line_2 = QtGui.QFrame(self.groupBokPer)
        self.line_2.setGeometry(QtCore.QRect(10, 102, 761, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.checkBoxSection = QtGui.QCheckBox(self.groupBokPer)
        self.checkBoxSection.setGeometry(QtCore.QRect(682, 120, 81, 31))
        self.checkBoxSection.setObjectName(_fromUtf8("checkBoxSection"))
        self.line_3 = QtGui.QFrame(self.groupBokPer)
        self.line_3.setGeometry(QtCore.QRect(10, 142, 761, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.groupBokPer)
        self.line_4.setGeometry(QtCore.QRect(652, 116, 20, 31))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.groupBokPer)
        self.line_5.setGeometry(QtCore.QRect(652, 78, 20, 31))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.checkBoxItem = QtGui.QCheckBox(self.groupBokPer)
        self.checkBoxItem.setGeometry(QtCore.QRect(682, 160, 81, 31))
        self.checkBoxItem.setObjectName(_fromUtf8("checkBoxItem"))
        self.line_6 = QtGui.QFrame(self.groupBokPer)
        self.line_6.setGeometry(QtCore.QRect(10, 186, 761, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_7 = QtGui.QFrame(self.groupBokPer)
        self.line_7.setGeometry(QtCore.QRect(652, 160, 20, 31))
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.checkBoxCust = QtGui.QCheckBox(self.groupBokPer)
        self.checkBoxCust.setGeometry(QtCore.QRect(682, 204, 81, 31))
        self.checkBoxCust.setObjectName(_fromUtf8("checkBoxCust"))
        self.line_8 = QtGui.QFrame(self.groupBokPer)
        self.line_8.setGeometry(QtCore.QRect(652, 204, 20, 31))
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.line_9 = QtGui.QFrame(self.groupBokPer)
        self.line_9.setGeometry(QtCore.QRect(10, 228, 761, 20))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.checkBoxEmployee = QtGui.QCheckBox(self.groupBokPer)
        self.checkBoxEmployee.setGeometry(QtCore.QRect(682, 244, 81, 31))
        self.checkBoxEmployee.setObjectName(_fromUtf8("checkBoxEmployee"))
        self.line_10 = QtGui.QFrame(self.groupBokPer)
        self.line_10.setGeometry(QtCore.QRect(652, 242, 20, 31))
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.line_11 = QtGui.QFrame(self.groupBokPer)
        self.line_11.setGeometry(QtCore.QRect(10, 270, 761, 16))
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.checkBoxUsers = QtGui.QCheckBox(self.groupBokPer)
        self.checkBoxUsers.setGeometry(QtCore.QRect(662, 284, 101, 31))
        self.checkBoxUsers.setObjectName(_fromUtf8("checkBoxUsers"))
        self.line_12 = QtGui.QFrame(self.groupBokPer)
        self.line_12.setGeometry(QtCore.QRect(652, 282, 20, 31))
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.line_13 = QtGui.QFrame(self.groupBokPer)
        self.line_13.setGeometry(QtCore.QRect(10, 310, 761, 20))
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.checkBoxSSection = QtGui.QCheckBox(self.groupBokPer)
        self.checkBoxSSection.setGeometry(QtCore.QRect(412, 120, 111, 31))
        self.checkBoxSSection.setObjectName(_fromUtf8("checkBoxSSection"))
        self.checkBoxSStor = QtGui.QCheckBox(self.groupBokPer)
        self.checkBoxSStor.setGeometry(QtCore.QRect(532, 117, 111, 31))
        self.checkBoxSStor.setObjectName(_fromUtf8("checkBoxSStor"))
        self.checkBoxSItem = QtGui.QCheckBox(self.groupBokPer)
        self.checkBoxSItem.setGeometry(QtCore.QRect(422, 160, 121, 31))
        self.checkBoxSItem.setObjectName(_fromUtf8("checkBoxSItem"))
        self.checkBoxAddItem = QtGui.QCheckBox(self.groupBokPer)
        self.checkBoxAddItem.setGeometry(QtCore.QRect(542, 160, 101, 31))
        self.checkBoxAddItem.setObjectName(_fromUtf8("checkBoxAddItem"))
        self.checkBoxSCatecory = QtGui.QCheckBox(self.groupBokPer)
        self.checkBoxSCatecory.setGeometry(QtCore.QRect(292, 160, 121, 31))
        self.checkBoxSCatecory.setObjectName(_fromUtf8("checkBoxSCatecory"))
        self.checkBoxSCust = QtGui.QCheckBox(self.groupBokPer)
        self.checkBoxSCust.setGeometry(QtCore.QRect(522, 200, 121, 31))
        self.checkBoxSCust.setObjectName(_fromUtf8("checkBoxSCust"))
        self.checkBox = QtGui.QCheckBox(self.groupBokPer)
        self.checkBox.setGeometry(QtCore.QRect(412, 242, 111, 31))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBoxSEmployee = QtGui.QCheckBox(self.groupBokPer)
        self.checkBoxSEmployee.setGeometry(QtCore.QRect(524, 242, 121, 31))
        self.checkBoxSEmployee.setObjectName(_fromUtf8("checkBoxSEmployee"))
        self.checkBoxViewUser = QtGui.QCheckBox(self.groupBokPer)
        self.checkBoxViewUser.setGeometry(QtCore.QRect(395, 282, 131, 31))
        self.checkBoxViewUser.setObjectName(_fromUtf8("checkBoxViewUser"))
        self.checkBoxAddUser = QtGui.QCheckBox(self.groupBokPer)
        self.checkBoxAddUser.setGeometry(QtCore.QRect(535, 282, 111, 31))
        self.checkBoxAddUser.setObjectName(_fromUtf8("checkBoxAddUser"))
        self.line_15 = QtGui.QFrame(self.groupBokPer)
        self.line_15.setGeometry(QtCore.QRect(10, 64, 761, 20))
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.checkBoxAll = QtGui.QCheckBox(self.groupBokPer)
        self.checkBoxAll.setGeometry(QtCore.QRect(660, 42, 101, 31))
        self.checkBoxAll.setObjectName(_fromUtf8("checkBoxAll"))
        self.labShowMenuPer = QtGui.QLabel(self.groupBokPer)
        self.labShowMenuPer.setGeometry(QtCore.QRect(10, 8, 23, 23))
        self.labShowMenuPer.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.labShowMenuPer.setText(_fromUtf8(""))
        self.labShowMenuPer.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/arrow-32.png")))
        self.labShowMenuPer.setScaledContents(True)
        self.labShowMenuPer.setObjectName(_fromUtf8("labShowMenuPer"))
        self.checkBoxSettings = QtGui.QCheckBox(self.groupBokPer)
        self.checkBoxSettings.setGeometry(QtCore.QRect(290, 80, 131, 31))
        self.checkBoxSettings.setObjectName(_fromUtf8("checkBoxSettings"))
        self.groupBoxButtonControl = QtGui.QGroupBox(Users)
        self.groupBoxButtonControl.setGeometry(QtCore.QRect(10, 280, 781, 61))
        self.groupBoxButtonControl.setTitle(_fromUtf8(""))
        self.groupBoxButtonControl.setObjectName(_fromUtf8("groupBoxButtonControl"))
        self.btnAddUser = QtGui.QPushButton(self.groupBoxButtonControl)
        self.btnAddUser.setGeometry(QtCore.QRect(630, 10, 141, 41))
        self.btnAddUser.setObjectName(_fromUtf8("btnAddUser"))
        self.btnSelectUsers = QtGui.QPushButton(self.groupBoxButtonControl)
        self.btnSelectUsers.setGeometry(QtCore.QRect(310, 10, 141, 41))
        self.btnSelectUsers.setObjectName(_fromUtf8("btnSelectUsers"))
        self.btnEditUser = QtGui.QPushButton(self.groupBoxButtonControl)
        self.btnEditUser.setEnabled(False)
        self.btnEditUser.setGeometry(QtCore.QRect(150, 10, 141, 41))
        self.btnEditUser.setObjectName(_fromUtf8("btnEditUser"))
        self.btnCancel = QtGui.QPushButton(self.groupBoxButtonControl)
        self.btnCancel.setEnabled(True)
        self.btnCancel.setGeometry(QtCore.QRect(470, 10, 141, 41))
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.labUserPassword = QtGui.QLabel(Users)
        self.labUserPassword.setGeometry(QtCore.QRect(215, 209, 71, 31))
        self.labUserPassword.setObjectName(_fromUtf8("labUserPassword"))
        self.labImageName = QtGui.QLabel(Users)
        self.labImageName.setGeometry(QtCore.QRect(300, 210, 71, 31))
        self.labImageName.setObjectName(_fromUtf8("labImageName"))
        self.labUserID = QtGui.QLabel(Users)
        self.labUserID.setGeometry(QtCore.QRect(370, 210, 71, 31))
        self.labUserID.setObjectName(_fromUtf8("labUserID"))

        self.retranslateUi(Users)
        QtCore.QMetaObject.connectSlotsByName(Users)
        Users.setTabOrder(self.textFullName, self.textNumberID)
        Users.setTabOrder(self.textNumberID, self.textUsername)
        Users.setTabOrder(self.textUsername, self.textPassword)
        Users.setTabOrder(self.textPassword, self.textEmail)
        Users.setTabOrder(self.textEmail, self.textNumberPhone)
        Users.setTabOrder(self.textNumberPhone, self.comboxSex)
        Users.setTabOrder(self.comboxSex, self.checkBoxGen)
        Users.setTabOrder(self.checkBoxGen, self.textCreatePasswordComplix)
        Users.setTabOrder(self.textCreatePasswordComplix, self.checkBoxCalc)
        Users.setTabOrder(self.checkBoxCalc, self.checkBoxChat)
        Users.setTabOrder(self.checkBoxChat, self.checkBoxSection)
        Users.setTabOrder(self.checkBoxSection, self.checkBoxItem)
        Users.setTabOrder(self.checkBoxItem, self.checkBoxCust)
        Users.setTabOrder(self.checkBoxCust, self.checkBoxEmployee)
        Users.setTabOrder(self.checkBoxEmployee, self.checkBoxUsers)
        Users.setTabOrder(self.checkBoxUsers, self.checkBoxSSection)
        Users.setTabOrder(self.checkBoxSSection, self.checkBoxSStor)
        Users.setTabOrder(self.checkBoxSStor, self.checkBoxSItem)
        Users.setTabOrder(self.checkBoxSItem, self.checkBoxAddItem)
        Users.setTabOrder(self.checkBoxAddItem, self.checkBoxSCatecory)
        Users.setTabOrder(self.checkBoxSCatecory, self.checkBoxSCust)
        Users.setTabOrder(self.checkBoxSCust, self.checkBox)
        Users.setTabOrder(self.checkBox, self.checkBoxSEmployee)
        Users.setTabOrder(self.checkBoxSEmployee, self.checkBoxViewUser)
        Users.setTabOrder(self.checkBoxViewUser, self.checkBoxAddUser)
        Users.setTabOrder(self.checkBoxAddUser, self.checkBoxAll)
        Users.setTabOrder(self.checkBoxAll, self.btnAddUser)
        Users.setTabOrder(self.btnAddUser, self.btnSelectUsers)
        Users.setTabOrder(self.btnSelectUsers, self.btnEditUser)

    def retranslateUi(self, Users):
        Users.setWindowTitle(_translate("Users", "اظافة مستخدم ", None))
        self.groupBox.setTitle(_translate("Users", "معلومات المستخدم", None))
        self.textEmail.setPlaceholderText(_translate("Users", "البريد الالكتروني", None))
        self.textNumberID.setPlaceholderText(_translate("Users", "الرقم الوطني", None))
        self.textFullName.setPlaceholderText(_translate("Users", "الاسم الكامل", None))
        self.textUsername.setPlaceholderText(_translate("Users", "اسم المستخدم ", None))
        self.textNumberPhone.setPlaceholderText(_translate("Users", "رقم الهاتف", None))
        self.textPassword.setPlaceholderText(_translate("Users", "كلمة المرور", None))
        self.labShowPassword.setToolTip(_translate("Users", "اظهار كلمة المرور", None))
        self.comboxSex.setItemText(0, _translate("Users", "جنس المستخدم", None))
        self.comboxSex.setItemText(1, _translate("Users", "ذكر", None))
        self.comboxSex.setItemText(2, _translate("Users", "انثى", None))
        self.labCreatePasswordComplix.setToolTip(_translate("Users", "انشاء كلمة مرور قوية", None))
        self.textPasswordShow.setPlaceholderText(_translate("Users", "كلمة المرور", None))
        self.groupBokPer.setTitle(_translate("Users", "صلاحيات المستخدم", None))
        self.checkBoxGen.setText(_translate("Users", "عام", None))
        self.checkBoxCalc.setText(_translate("Users", "ادارت المبيعات ", None))
        self.checkBoxChat.setText(_translate("Users", "محادثه", None))
        self.checkBoxSection.setText(_translate("Users", "الاقسام", None))
        self.checkBoxItem.setText(_translate("Users", "المواد", None))
        self.checkBoxCust.setText(_translate("Users", "العملاء", None))
        self.checkBoxEmployee.setText(_translate("Users", "الموظفين", None))
        self.checkBoxUsers.setText(_translate("Users", "المستخدمين", None))
        self.checkBoxSSection.setText(_translate("Users", "اعدادات الاقسام", None))
        self.checkBoxSStor.setText(_translate("Users", "اعدادات المخازن", None))
        self.checkBoxSItem.setText(_translate("Users", "اعدادات المنتجات", None))
        self.checkBoxAddItem.setText(_translate("Users", "اظافة منتج ", None))
        self.checkBoxSCatecory.setText(_translate("Users", "اعدادات الاصناف", None))
        self.checkBoxSCust.setText(_translate("Users", "اعدادات العملاء", None))
        self.checkBox.setText(_translate("Users", "دوام الموظفين", None))
        self.checkBoxSEmployee.setText(_translate("Users", "اعدادات الموظين", None))
        self.checkBoxViewUser.setText(_translate("Users", "عرض المستخدمين", None))
        self.checkBoxAddUser.setText(_translate("Users", "اظافة مستخدم", None))
        self.checkBoxAll.setText(_translate("Users", "كل الصلاحيات", None))
        self.labShowMenuPer.setToolTip(_translate("Users", "اظهار قائمة الصلاحيات", None))
        self.checkBoxSettings.setText(_translate("Users", "اعدادات البرنامج ", None))
        self.btnAddUser.setText(_translate("Users", "اظافة مستخدم", None))
        self.btnSelectUsers.setText(_translate("Users", "اختيار مستخدم ", None))
        self.btnEditUser.setText(_translate("Users", "تعديل المستخدم", None))
        self.btnCancel.setText(_translate("Users", "الغاء", None))
        self.labUserPassword.setText(_translate("Users", "UserPassword", None))
        self.labImageName.setText(_translate("Users", "ImagesName", None))
        self.labUserID.setText(_translate("Users", "UserID", None))

import pathIcon_rc
