# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Customers.ui'
#
# Created: Tue Apr 25 15:44:01 2017
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Customers(object):
    def setupUi(self, Customers):
        Customers.setObjectName(_fromUtf8("Customers"))
        Customers.setWindowModality(QtCore.Qt.ApplicationModal)
        Customers.resize(823, 535)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/UserDefault.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Customers.setWindowIcon(icon)
        Customers.setLayoutDirection(QtCore.Qt.RightToLeft)
        Customers.setAutoFillBackground(False)
        Customers.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Jordan))
        self.groupBox = QtGui.QGroupBox(Customers)
        self.groupBox.setGeometry(QtCore.QRect(7, 5, 811, 271))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lineEditCustomerName = QtGui.QLineEdit(self.groupBox)
        self.lineEditCustomerName.setGeometry(QtCore.QRect(520, 14, 281, 31))
        self.lineEditCustomerName.setMaxLength(49)
        self.lineEditCustomerName.setObjectName(_fromUtf8("lineEditCustomerName"))
        self.lineEditCustomerPhone = QtGui.QLineEdit(self.groupBox)
        self.lineEditCustomerPhone.setGeometry(QtCore.QRect(214, 64, 281, 31))
        self.lineEditCustomerPhone.setMaxLength(20)
        self.lineEditCustomerPhone.setObjectName(_fromUtf8("lineEditCustomerPhone"))
        self.lineEditCustomerEmail = QtGui.QLineEdit(self.groupBox)
        self.lineEditCustomerEmail.setGeometry(QtCore.QRect(215, 14, 281, 31))
        self.lineEditCustomerEmail.setMaxLength(49)
        self.lineEditCustomerEmail.setObjectName(_fromUtf8("lineEditCustomerEmail"))
        self.comboBoxSex = QtGui.QComboBox(self.groupBox)
        self.comboBoxSex.setGeometry(QtCore.QRect(215, 115, 281, 31))
        self.comboBoxSex.setObjectName(_fromUtf8("comboBoxSex"))
        self.comboBoxSex.addItem(_fromUtf8(""))
        self.comboBoxSex.addItem(_fromUtf8(""))
        self.comboBoxSex.addItem(_fromUtf8(""))
        self.labCustomerImage = QtGui.QLabel(self.groupBox)
        self.labCustomerImage.setGeometry(QtCore.QRect(10, 10, 191, 201))
        self.labCustomerImage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labCustomerImage.setText(_fromUtf8(""))
        self.labCustomerImage.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/UserDefault.png")))
        self.labCustomerImage.setScaledContents(True)
        self.labCustomerImage.setObjectName(_fromUtf8("labCustomerImage"))
        self.btnCustomerAdd = QtGui.QPushButton(self.groupBox)
        self.btnCustomerAdd.setGeometry(QtCore.QRect(690, 170, 111, 41))
        self.btnCustomerAdd.setObjectName(_fromUtf8("btnCustomerAdd"))
        self.btnCustomerNotActivet = QtGui.QPushButton(self.groupBox)
        self.btnCustomerNotActivet.setGeometry(QtCore.QRect(450, 170, 111, 41))
        self.btnCustomerNotActivet.setObjectName(_fromUtf8("btnCustomerNotActivet"))
        self.plainTextEditCustomerAddress = QtGui.QPlainTextEdit(self.groupBox)
        self.plainTextEditCustomerAddress.setGeometry(QtCore.QRect(520, 54, 281, 91))
        self.plainTextEditCustomerAddress.setMaximumBlockCount(20)
        self.plainTextEditCustomerAddress.setObjectName(_fromUtf8("plainTextEditCustomerAddress"))
        self.btnCustomerActive = QtGui.QPushButton(self.groupBox)
        self.btnCustomerActive.setEnabled(False)
        self.btnCustomerActive.setGeometry(QtCore.QRect(330, 170, 111, 41))
        self.btnCustomerActive.setObjectName(_fromUtf8("btnCustomerActive"))
        self.btnCustomerEdit = QtGui.QPushButton(self.groupBox)
        self.btnCustomerEdit.setEnabled(False)
        self.btnCustomerEdit.setGeometry(QtCore.QRect(570, 170, 111, 41))
        self.btnCustomerEdit.setObjectName(_fromUtf8("btnCustomerEdit"))
        self.btnCancel = QtGui.QPushButton(self.groupBox)
        self.btnCancel.setGeometry(QtCore.QRect(210, 170, 111, 41))
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.lineEditCustomerSearch = QtGui.QLineEdit(self.groupBox)
        self.lineEditCustomerSearch.setGeometry(QtCore.QRect(420, 230, 381, 31))
        self.lineEditCustomerSearch.setMaxLength(50)
        self.lineEditCustomerSearch.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditCustomerSearch.setObjectName(_fromUtf8("lineEditCustomerSearch"))
        self.comboBoxSelectActive = QtGui.QComboBox(self.groupBox)
        self.comboBoxSelectActive.setGeometry(QtCore.QRect(230, 230, 181, 31))
        self.comboBoxSelectActive.setObjectName(_fromUtf8("comboBoxSelectActive"))
        self.comboBoxSelectActive.addItem(_fromUtf8(""))
        self.comboBoxSelectActive.addItem(_fromUtf8(""))
        self.labUserID = QtGui.QLabel(self.groupBox)
        self.labUserID.setGeometry(QtCore.QRect(160, 110, 46, 13))
        self.labUserID.setObjectName(_fromUtf8("labUserID"))
        self.labCustID = QtGui.QLabel(self.groupBox)
        self.labCustID.setGeometry(QtCore.QRect(160, 90, 46, 13))
        self.labCustID.setObjectName(_fromUtf8("labCustID"))
        self.tableCustomer = QtGui.QTableWidget(Customers)
        self.tableCustomer.setGeometry(QtCore.QRect(6, 290, 811, 241))
        self.tableCustomer.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableCustomer.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableCustomer.setObjectName(_fromUtf8("tableCustomer"))
        self.tableCustomer.setColumnCount(8)
        self.tableCustomer.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableCustomer.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableCustomer.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableCustomer.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableCustomer.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableCustomer.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableCustomer.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableCustomer.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableCustomer.setHorizontalHeaderItem(7, item)

        self.retranslateUi(Customers)
        QtCore.QMetaObject.connectSlotsByName(Customers)
        Customers.setTabOrder(self.lineEditCustomerName, self.lineEditCustomerEmail)
        Customers.setTabOrder(self.lineEditCustomerEmail, self.plainTextEditCustomerAddress)
        Customers.setTabOrder(self.plainTextEditCustomerAddress, self.lineEditCustomerPhone)
        Customers.setTabOrder(self.lineEditCustomerPhone, self.comboBoxSex)
        Customers.setTabOrder(self.comboBoxSex, self.btnCustomerAdd)
        Customers.setTabOrder(self.btnCustomerAdd, self.btnCustomerNotActivet)
        Customers.setTabOrder(self.btnCustomerNotActivet, self.tableCustomer)
        Customers.setTabOrder(self.tableCustomer, self.btnCustomerActive)
        Customers.setTabOrder(self.btnCustomerActive, self.btnCustomerEdit)
        Customers.setTabOrder(self.btnCustomerEdit, self.btnCancel)
        Customers.setTabOrder(self.btnCancel, self.lineEditCustomerSearch)
        Customers.setTabOrder(self.lineEditCustomerSearch, self.comboBoxSelectActive)

    def retranslateUi(self, Customers):
        Customers.setWindowTitle(_translate("Customers", "العملاء", None))
        self.lineEditCustomerName.setPlaceholderText(_translate("Customers", "اسم المستخدم", None))
        self.lineEditCustomerPhone.setPlaceholderText(_translate("Customers", "رقم العميل", None))
        self.lineEditCustomerEmail.setPlaceholderText(_translate("Customers", "اميل العميل", None))
        self.comboBoxSex.setItemText(0, _translate("Customers", "جنس العميل", None))
        self.comboBoxSex.setItemText(1, _translate("Customers", "ذكر", None))
        self.comboBoxSex.setItemText(2, _translate("Customers", "انثى", None))
        self.btnCustomerAdd.setText(_translate("Customers", "اظافة", None))
        self.btnCustomerNotActivet.setText(_translate("Customers", "الغاء العميل", None))
        self.btnCustomerActive.setText(_translate("Customers", "تفعيل العميل", None))
        self.btnCustomerEdit.setText(_translate("Customers", "تعديل العميل", None))
        self.btnCancel.setText(_translate("Customers", "الغاء", None))
        self.lineEditCustomerSearch.setPlaceholderText(_translate("Customers", "اكتوب ما تود البحث عنه", None))
        self.comboBoxSelectActive.setItemText(0, _translate("Customers", "العملاء الفعالين", None))
        self.comboBoxSelectActive.setItemText(1, _translate("Customers", "العملاء الغير فعالين", None))
        self.labUserID.setText(_translate("Customers", "UserID", None))
        self.labCustID.setText(_translate("Customers", "UserCust", None))
        item = self.tableCustomer.horizontalHeaderItem(0)
        item.setText(_translate("Customers", "معرف العميل", None))
        item = self.tableCustomer.horizontalHeaderItem(1)
        item.setText(_translate("Customers", "اسم العميل", None))
        item = self.tableCustomer.horizontalHeaderItem(2)
        item.setText(_translate("Customers", "اميل العميل", None))
        item = self.tableCustomer.horizontalHeaderItem(3)
        item.setText(_translate("Customers", "رقم العميل", None))
        item = self.tableCustomer.horizontalHeaderItem(4)
        item.setText(_translate("Customers", "تاريخ الاظافة", None))
        item = self.tableCustomer.horizontalHeaderItem(5)
        item.setText(_translate("Customers", "اسم المظيف", None))
        item = self.tableCustomer.horizontalHeaderItem(6)
        item.setText(_translate("Customers", "جنس العميل", None))
        item = self.tableCustomer.horizontalHeaderItem(7)
        item.setText(_translate("Customers", "عنوان العميل", None))

import pathIcon_rc
