# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\employes.ui'
#
# Created: Sat Apr 15 17:50:45 2017
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_employes(object):
    def setupUi(self, employes):
        employes.setObjectName(_fromUtf8("employes"))
        employes.setWindowModality(QtCore.Qt.ApplicationModal)
        employes.resize(984, 569)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/employes.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        employes.setWindowIcon(icon)
        employes.setLayoutDirection(QtCore.Qt.RightToLeft)
        employes.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Jordan))
        self.groupBox = QtGui.QGroupBox(employes)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 971, 211))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.labEmploye = QtGui.QLabel(self.groupBox)
        self.labEmploye.setGeometry(QtCore.QRect(7, 10, 191, 191))
        self.labEmploye.setText(_fromUtf8(""))
        self.labEmploye.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/employes.png")))
        self.labEmploye.setScaledContents(True)
        self.labEmploye.setObjectName(_fromUtf8("labEmploye"))
        self.textEmploAge = QtGui.QLineEdit(self.groupBox)
        self.textEmploAge.setGeometry(QtCore.QRect(470, 50, 241, 31))
        self.textEmploAge.setMaxLength(3)
        self.textEmploAge.setObjectName(_fromUtf8("textEmploAge"))
        self.textEmploName = QtGui.QLineEdit(self.groupBox)
        self.textEmploName.setGeometry(QtCore.QRect(720, 10, 241, 31))
        self.textEmploName.setMaxLength(50)
        self.textEmploName.setObjectName(_fromUtf8("textEmploName"))
        self.textEmploNumberID = QtGui.QLineEdit(self.groupBox)
        self.textEmploNumberID.setGeometry(QtCore.QRect(470, 10, 241, 31))
        self.textEmploNumberID.setMaxLength(20)
        self.textEmploNumberID.setObjectName(_fromUtf8("textEmploNumberID"))
        self.textEmploNumberPhone = QtGui.QLineEdit(self.groupBox)
        self.textEmploNumberPhone.setGeometry(QtCore.QRect(220, 10, 241, 31))
        self.textEmploNumberPhone.setMaxLength(20)
        self.textEmploNumberPhone.setObjectName(_fromUtf8("textEmploNumberPhone"))
        self.comBoxEmploSection = QtGui.QComboBox(self.groupBox)
        self.comBoxEmploSection.setGeometry(QtCore.QRect(220, 90, 241, 31))
        self.comBoxEmploSection.setObjectName(_fromUtf8("comBoxEmploSection"))
        self.comBoxEmploSection.addItem(_fromUtf8(""))
        self.textEmploSalary = QtGui.QLineEdit(self.groupBox)
        self.textEmploSalary.setGeometry(QtCore.QRect(470, 90, 241, 31))
        self.textEmploSalary.setMaxLength(10)
        self.textEmploSalary.setObjectName(_fromUtf8("textEmploSalary"))
        self.textEmploAddreass = QtGui.QPlainTextEdit(self.groupBox)
        self.textEmploAddreass.setGeometry(QtCore.QRect(720, 50, 241, 71))
        self.textEmploAddreass.setObjectName(_fromUtf8("textEmploAddreass"))
        self.comboxEmploSex = QtGui.QComboBox(self.groupBox)
        self.comboxEmploSex.setGeometry(QtCore.QRect(220, 50, 241, 31))
        self.comboxEmploSex.setObjectName(_fromUtf8("comboxEmploSex"))
        self.comboxEmploSex.addItem(_fromUtf8(""))
        self.comboxEmploSex.addItem(_fromUtf8(""))
        self.comboxEmploSex.addItem(_fromUtf8(""))
        self.btnEmploAdd = QtGui.QPushButton(self.groupBox)
        self.btnEmploAdd.setGeometry(QtCore.QRect(820, 146, 141, 41))
        self.btnEmploAdd.setAutoExclusive(False)
        self.btnEmploAdd.setObjectName(_fromUtf8("btnEmploAdd"))
        self.btnEmploNotActive = QtGui.QPushButton(self.groupBox)
        self.btnEmploNotActive.setEnabled(True)
        self.btnEmploNotActive.setGeometry(QtCore.QRect(520, 146, 141, 41))
        self.btnEmploNotActive.setObjectName(_fromUtf8("btnEmploNotActive"))
        self.btnEmploEdit = QtGui.QPushButton(self.groupBox)
        self.btnEmploEdit.setEnabled(False)
        self.btnEmploEdit.setGeometry(QtCore.QRect(670, 146, 141, 41))
        self.btnEmploEdit.setObjectName(_fromUtf8("btnEmploEdit"))
        self.btnEmploActive = QtGui.QPushButton(self.groupBox)
        self.btnEmploActive.setEnabled(False)
        self.btnEmploActive.setGeometry(QtCore.QRect(370, 146, 141, 41))
        self.btnEmploActive.setObjectName(_fromUtf8("btnEmploActive"))
        self.btnCancel = QtGui.QPushButton(self.groupBox)
        self.btnCancel.setEnabled(True)
        self.btnCancel.setGeometry(QtCore.QRect(220, 146, 141, 41))
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.labUserID = QtGui.QLabel(self.groupBox)
        self.labUserID.setGeometry(QtCore.QRect(230, 190, 16, 16))
        self.labUserID.setObjectName(_fromUtf8("labUserID"))
        self.textEmploSearch = QtGui.QLineEdit(employes)
        self.textEmploSearch.setGeometry(QtCore.QRect(578, 230, 401, 31))
        self.textEmploSearch.setAlignment(QtCore.Qt.AlignCenter)
        self.textEmploSearch.setObjectName(_fromUtf8("textEmploSearch"))
        self.comboxEmploActive = QtGui.QComboBox(employes)
        self.comboxEmploActive.setGeometry(QtCore.QRect(380, 230, 181, 31))
        self.comboxEmploActive.setObjectName(_fromUtf8("comboxEmploActive"))
        self.comboxEmploActive.addItem(_fromUtf8(""))
        self.comboxEmploActive.addItem(_fromUtf8(""))
        self.labEmploNumber = QtGui.QLabel(employes)
        self.labEmploNumber.setGeometry(QtCore.QRect(10, 230, 81, 31))
        self.labEmploNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.labEmploNumber.setObjectName(_fromUtf8("labEmploNumber"))
        self.tableEmployes = QtGui.QTableWidget(employes)
        self.tableEmployes.setGeometry(QtCore.QRect(9, 270, 971, 291))
        self.tableEmployes.setObjectName(_fromUtf8("tableEmployes"))
        self.tableEmployes.setColumnCount(8)
        self.tableEmployes.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableEmployes.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableEmployes.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableEmployes.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableEmployes.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableEmployes.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableEmployes.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableEmployes.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableEmployes.setHorizontalHeaderItem(7, item)
        self.label_3 = QtGui.QLabel(employes)
        self.label_3.setGeometry(QtCore.QRect(100, 230, 101, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.comboxEmploReport = QtGui.QComboBox(employes)
        self.comboxEmploReport.setGeometry(QtCore.QRect(210, 230, 161, 31))
        self.comboxEmploReport.setObjectName(_fromUtf8("comboxEmploReport"))
        self.comboxEmploReport.addItem(_fromUtf8(""))
        self.comboxEmploReport.addItem(_fromUtf8(""))

        self.retranslateUi(employes)
        QtCore.QMetaObject.connectSlotsByName(employes)
        employes.setTabOrder(self.textEmploName, self.textEmploNumberID)
        employes.setTabOrder(self.textEmploNumberID, self.textEmploNumberPhone)
        employes.setTabOrder(self.textEmploNumberPhone, self.textEmploAddreass)
        employes.setTabOrder(self.textEmploAddreass, self.textEmploAge)
        employes.setTabOrder(self.textEmploAge, self.textEmploSalary)
        employes.setTabOrder(self.textEmploSalary, self.comboxEmploSex)
        employes.setTabOrder(self.comboxEmploSex, self.comBoxEmploSection)
        employes.setTabOrder(self.comBoxEmploSection, self.btnEmploAdd)
        employes.setTabOrder(self.btnEmploAdd, self.textEmploSearch)
        employes.setTabOrder(self.textEmploSearch, self.comboxEmploActive)
        employes.setTabOrder(self.comboxEmploActive, self.btnCancel)
        employes.setTabOrder(self.btnCancel, self.tableEmployes)
        employes.setTabOrder(self.tableEmployes, self.btnEmploEdit)
        employes.setTabOrder(self.btnEmploEdit, self.btnEmploActive)
        employes.setTabOrder(self.btnEmploActive, self.btnEmploNotActive)

    def retranslateUi(self, employes):
        employes.setWindowTitle(_translate("employes", "الموظفين", None))
        self.textEmploAge.setPlaceholderText(_translate("employes", "عمر الموظف", None))
        self.textEmploName.setPlaceholderText(_translate("employes", "اسم الموظف", None))
        self.textEmploNumberID.setPlaceholderText(_translate("employes", "الرقم الوطني", None))
        self.textEmploNumberPhone.setPlaceholderText(_translate("employes", "رقم الهاتف", None))
        self.comBoxEmploSection.setItemText(0, _translate("employes", "قسم عمل الموظف", None))
        self.textEmploSalary.setPlaceholderText(_translate("employes", "راتب الموظف", None))
        self.comboxEmploSex.setItemText(0, _translate("employes", "جنس الموظف", None))
        self.comboxEmploSex.setItemText(1, _translate("employes", "ذكر", None))
        self.comboxEmploSex.setItemText(2, _translate("employes", "انثى", None))
        self.btnEmploAdd.setText(_translate("employes", "اظافة", None))
        self.btnEmploNotActive.setText(_translate("employes", "الغاء الموظف", None))
        self.btnEmploEdit.setText(_translate("employes", "تعديل", None))
        self.btnEmploActive.setText(_translate("employes", "تفعيل الموظف", None))
        self.btnCancel.setText(_translate("employes", "الغاء", None))
        self.labUserID.setText(_translate("employes", "UserID", None))
        self.textEmploSearch.setPlaceholderText(_translate("employes", "اكتب ما تود البحث عنه ", None))
        self.comboxEmploActive.setItemText(0, _translate("employes", "الموظفين النشطين", None))
        self.comboxEmploActive.setItemText(1, _translate("employes", "الموظفين الغير نشطين", None))
        self.labEmploNumber.setText(_translate("employes", "0", None))
        item = self.tableEmployes.horizontalHeaderItem(0)
        item.setText(_translate("employes", "الرقم الوطني", None))
        item = self.tableEmployes.horizontalHeaderItem(1)
        item.setText(_translate("employes", "الاسم", None))
        item = self.tableEmployes.horizontalHeaderItem(2)
        item.setText(_translate("employes", "الراتب", None))
        item = self.tableEmployes.horizontalHeaderItem(3)
        item.setText(_translate("employes", "العمر", None))
        item = self.tableEmployes.horizontalHeaderItem(4)
        item.setText(_translate("employes", "القسم", None))
        item = self.tableEmployes.horizontalHeaderItem(5)
        item.setText(_translate("employes", "تاريخ التوظيف", None))
        item = self.tableEmployes.horizontalHeaderItem(6)
        item.setText(_translate("employes", "رقم الهاتف", None))
        item = self.tableEmployes.horizontalHeaderItem(7)
        item.setText(_translate("employes", "اسم المضيف", None))
        self.label_3.setText(_translate("employes", "عدد الموظفين : ", None))
        self.comboxEmploReport.setItemText(0, _translate("employes", "التقارير", None))
        self.comboxEmploReport.setItemText(1, _translate("employes", "كل الموظفين", None))

import pathIcon_rc
