# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created: Fri Apr 21 10:12:06 2017
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(751, 551)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Arabic Kufi"))
        font.setPointSize(12)
        font.setItalic(False)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Jordan))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.labUserID = QtGui.QLabel(self.centralwidget)
        self.labUserID.setGeometry(QtCore.QRect(380, 100, 41, 31))
        self.labUserID.setObjectName(_fromUtf8("labUserID"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 751, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu1 = QtGui.QMenu(self.menubar)
        self.menu1.setObjectName(_fromUtf8("menu1"))
        self.menu2 = QtGui.QMenu(self.menubar)
        self.menu2.setObjectName(_fromUtf8("menu2"))
        self.menu3 = QtGui.QMenu(self.menubar)
        self.menu3.setObjectName(_fromUtf8("menu3"))
        self.menu4 = QtGui.QMenu(self.menubar)
        self.menu4.setObjectName(_fromUtf8("menu4"))
        self.menu5 = QtGui.QMenu(self.menubar)
        self.menu5.setObjectName(_fromUtf8("menu5"))
        self.menu6 = QtGui.QMenu(self.menubar)
        self.menu6.setObjectName(_fromUtf8("menu6"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.editProfile = QtGui.QAction(MainWindow)
        self.editProfile.setObjectName(_fromUtf8("editProfile"))
        self.logOut = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/closeServer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logOut.setIcon(icon1)
        self.logOut.setIconVisibleInMenu(False)
        self.logOut.setObjectName(_fromUtf8("logOut"))
        self.addUser = QtGui.QAction(MainWindow)
        self.addUser.setObjectName(_fromUtf8("addUser"))
        self.settingUser = QtGui.QAction(MainWindow)
        self.settingUser.setObjectName(_fromUtf8("settingUser"))
        self.action_5 = QtGui.QAction(MainWindow)
        self.action_5.setObjectName(_fromUtf8("action_5"))
        self.managmentSection = QtGui.QAction(MainWindow)
        self.managmentSection.setObjectName(_fromUtf8("managmentSection"))
        self.addItem = QtGui.QAction(MainWindow)
        self.addItem.setObjectName(_fromUtf8("addItem"))
        self.action_9 = QtGui.QAction(MainWindow)
        self.action_9.setObjectName(_fromUtf8("action_9"))
        self.SettingCustomers = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/UserDefault.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SettingCustomers.setIcon(icon2)
        self.SettingCustomers.setObjectName(_fromUtf8("SettingCustomers"))
        self.fullScreen = QtGui.QAction(MainWindow)
        self.fullScreen.setObjectName(_fromUtf8("fullScreen"))
        self.manegmentCategory = QtGui.QAction(MainWindow)
        self.manegmentCategory.setObjectName(_fromUtf8("manegmentCategory"))
        self.SettingStor = QtGui.QAction(MainWindow)
        self.SettingStor.setObjectName(_fromUtf8("SettingStor"))
        self.manegmentItem = QtGui.QAction(MainWindow)
        self.manegmentItem.setObjectName(_fromUtf8("manegmentItem"))
        self.SettingEmployes = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/employes.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SettingEmployes.setIcon(icon3)
        self.SettingEmployes.setObjectName(_fromUtf8("SettingEmployes"))
        self.action_2 = QtGui.QAction(MainWindow)
        self.action_2.setObjectName(_fromUtf8("action_2"))
        self.action_3 = QtGui.QAction(MainWindow)
        self.action_3.setObjectName(_fromUtf8("action_3"))
        self.action_4 = QtGui.QAction(MainWindow)
        self.action_4.setObjectName(_fromUtf8("action_4"))
        self.action_6 = QtGui.QAction(MainWindow)
        self.action_6.setObjectName(_fromUtf8("action_6"))
        self.action_7 = QtGui.QAction(MainWindow)
        self.action_7.setObjectName(_fromUtf8("action_7"))
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_8 = QtGui.QAction(MainWindow)
        self.action_8.setObjectName(_fromUtf8("action_8"))
        self.action_10 = QtGui.QAction(MainWindow)
        self.action_10.setObjectName(_fromUtf8("action_10"))
        self.action_11 = QtGui.QAction(MainWindow)
        self.action_11.setObjectName(_fromUtf8("action_11"))
        self.action_12 = QtGui.QAction(MainWindow)
        self.action_12.setObjectName(_fromUtf8("action_12"))
        self.action_13 = QtGui.QAction(MainWindow)
        self.action_13.setObjectName(_fromUtf8("action_13"))
        self.calculator = QtGui.QAction(MainWindow)
        self.calculator.setIconVisibleInMenu(True)
        self.calculator.setObjectName(_fromUtf8("calculator"))
        self.menuAddUser = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/add-user.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuAddUser.setIcon(icon4)
        self.menuAddUser.setObjectName(_fromUtf8("menuAddUser"))
        self.menuViewUser = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/users.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuViewUser.setIcon(icon5)
        self.menuViewUser.setObjectName(_fromUtf8("menuViewUser"))
        self.menuChat = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/chat.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuChat.setIcon(icon6)
        self.menuChat.setObjectName(_fromUtf8("menuChat"))
        self.mainSales = QtGui.QAction(MainWindow)
        self.mainSales.setObjectName(_fromUtf8("mainSales"))
        self.menuSettingAll = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/Settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuSettingAll.setIcon(icon7)
        self.menuSettingAll.setObjectName(_fromUtf8("menuSettingAll"))
        self.menu1.addAction(self.mainSales)
        self.menu1.addAction(self.menuChat)
        self.menu1.addAction(self.menuSettingAll)
        self.menu1.addSeparator()
        self.menu1.addAction(self.logOut)
        self.menu2.addAction(self.managmentSection)
        self.menu2.addAction(self.SettingStor)
        self.menu3.addAction(self.addItem)
        self.menu3.addAction(self.manegmentItem)
        self.menu3.addAction(self.manegmentCategory)
        self.menu4.addAction(self.SettingCustomers)
        self.menu5.addAction(self.SettingEmployes)
        self.menu6.addAction(self.menuAddUser)
        self.menu6.addAction(self.menuViewUser)
        self.menubar.addAction(self.menu1.menuAction())
        self.menubar.addAction(self.menu2.menuAction())
        self.menubar.addAction(self.menu3.menuAction())
        self.menubar.addAction(self.menu4.menuAction())
        self.menubar.addAction(self.menu5.menuAction())
        self.menubar.addAction(self.menu6.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Shop Management System ", None))
        self.labUserID.setText(_translate("MainWindow", "1", None))
        self.menu1.setTitle(_translate("MainWindow", "عام", None))
        self.menu2.setTitle(_translate("MainWindow", "الاقسام", None))
        self.menu3.setTitle(_translate("MainWindow", "المواد", None))
        self.menu4.setTitle(_translate("MainWindow", "العملاء", None))
        self.menu5.setTitle(_translate("MainWindow", "الموظفين", None))
        self.menu6.setTitle(_translate("MainWindow", "المستخدمين", None))
        self.editProfile.setText(_translate("MainWindow", "اعدادات الحساب", None))
        self.editProfile.setIconText(_translate("MainWindow", "اعدادات الحساب", None))
        self.logOut.setText(_translate("MainWindow", "تسجيل الخروج", None))
        self.addUser.setText(_translate("MainWindow", "اظافة مستخدم", None))
        self.settingUser.setText(_translate("MainWindow", "اعدادات المستخدمين", None))
        self.action_5.setText(_translate("MainWindow", "اظافة قسم", None))
        self.managmentSection.setText(_translate("MainWindow", "اعدادات الاقسام", None))
        self.addItem.setText(_translate("MainWindow", "اظافة منتج", None))
        self.action_9.setText(_translate("MainWindow", "اظافة عميل", None))
        self.SettingCustomers.setText(_translate("MainWindow", "اعدادات العملاء", None))
        self.fullScreen.setText(_translate("MainWindow", "تصغير الشاشه", None))
        self.manegmentCategory.setText(_translate("MainWindow", "اعدادات الاصناف", None))
        self.SettingStor.setText(_translate("MainWindow", "اعدادات المخازن", None))
        self.manegmentItem.setText(_translate("MainWindow", "اعدادات المنتجات ", None))
        self.SettingEmployes.setText(_translate("MainWindow", "اعدادات الموظفين", None))
        self.action_2.setText(_translate("MainWindow", "دوام الموظفين", None))
        self.action_3.setText(_translate("MainWindow", "اعدادات الاتصال", None))
        self.action_4.setText(_translate("MainWindow", "العملاء", None))
        self.action_6.setText(_translate("MainWindow", "الموظفين", None))
        self.action_7.setText(_translate("MainWindow", "الاقسام", None))
        self.action.setText(_translate("MainWindow", "الموظفين ", None))
        self.action_8.setText(_translate("MainWindow", "المستخدمين ", None))
        self.action_10.setText(_translate("MainWindow", "العملاء", None))
        self.action_11.setText(_translate("MainWindow", "الاقسام", None))
        self.action_12.setText(_translate("MainWindow", "الاصناف", None))
        self.action_13.setText(_translate("MainWindow", "المنتجات ", None))
        self.calculator.setText(_translate("MainWindow", "اله حاسبة", None))
        self.menuAddUser.setText(_translate("MainWindow", "اظافة مستخدم ", None))
        self.menuViewUser.setText(_translate("MainWindow", " عرض المستخدمين ", None))
        self.menuChat.setText(_translate("MainWindow", "محادثة", None))
        self.mainSales.setText(_translate("MainWindow", "ادارة المبيعات ", None))
        self.menuSettingAll.setText(_translate("MainWindow", "اعدادات البرنامج ", None))

import pathIcon_rc
