# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sales.ui'
#
# Created: Sat Apr 15 18:19:15 2017
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_sales(object):
    def setupUi(self, sales):
        sales.setObjectName(_fromUtf8("sales"))
        sales.resize(971, 584)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/SalesAdministration.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        sales.setWindowIcon(icon)
        sales.setLayoutDirection(QtCore.Qt.RightToLeft)
        sales.setStyleSheet(_fromUtf8(""))
        sales.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.SaudiArabia))
        self.groupBox = QtGui.QGroupBox(sales)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 951, 51))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.labAddSales = QtGui.QLabel(self.groupBox)
        self.labAddSales.setGeometry(QtCore.QRect(900, 10, 46, 31))
        self.labAddSales.setText(_fromUtf8(""))
        self.labAddSales.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/addSales.png")))
        self.labAddSales.setScaledContents(True)
        self.labAddSales.setObjectName(_fromUtf8("labAddSales"))
        self.labSave = QtGui.QLabel(self.groupBox)
        self.labSave.setEnabled(False)
        self.labSave.setGeometry(QtCore.QRect(844, 10, 46, 31))
        self.labSave.setText(_fromUtf8(""))
        self.labSave.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/save.png")))
        self.labSave.setScaledContents(True)
        self.labSave.setObjectName(_fromUtf8("labSave"))
        self.labPrint = QtGui.QLabel(self.groupBox)
        self.labPrint.setEnabled(False)
        self.labPrint.setGeometry(QtCore.QRect(780, 10, 46, 31))
        self.labPrint.setText(_fromUtf8(""))
        self.labPrint.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/printer.png")))
        self.labPrint.setScaledContents(True)
        self.labPrint.setObjectName(_fromUtf8("labPrint"))
        self.labCalc = QtGui.QLabel(self.groupBox)
        self.labCalc.setGeometry(QtCore.QRect(720, 10, 46, 31))
        self.labCalc.setText(_fromUtf8(""))
        self.labCalc.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/calculator.png")))
        self.labCalc.setScaledContents(True)
        self.labCalc.setObjectName(_fromUtf8("labCalc"))
        self.groupBox_2 = QtGui.QGroupBox(sales)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 70, 951, 121))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(840, 10, 101, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.labNameSalse = QtGui.QLabel(self.groupBox_2)
        self.labNameSalse.setGeometry(QtCore.QRect(580, 10, 241, 31))
        self.labNameSalse.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labNameSalse.setObjectName(_fromUtf8("labNameSalse"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(840, 44, 101, 31))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.labBillID = QtGui.QLabel(self.groupBox_2)
        self.labBillID.setGeometry(QtCore.QRect(580, 45, 241, 31))
        self.labBillID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labBillID.setObjectName(_fromUtf8("labBillID"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(840, 80, 101, 31))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.labNameSection = QtGui.QLabel(self.groupBox_2)
        self.labNameSection.setGeometry(QtCore.QRect(580, 81, 241, 31))
        self.labNameSection.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labNameSection.setObjectName(_fromUtf8("labNameSection"))
        self.line = QtGui.QFrame(self.groupBox_2)
        self.line.setGeometry(QtCore.QRect(560, 10, 20, 101))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.labSelectCus = QtGui.QLabel(self.groupBox_2)
        self.labSelectCus.setEnabled(False)
        self.labSelectCus.setGeometry(QtCore.QRect(20, 10, 141, 101))
        self.labSelectCus.setText(_fromUtf8(""))
        self.labSelectCus.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/UserDefault.png")))
        self.labSelectCus.setScaledContents(True)
        self.labSelectCus.setObjectName(_fromUtf8("labSelectCus"))
        self.labNameCus = QtGui.QLabel(self.groupBox_2)
        self.labNameCus.setGeometry(QtCore.QRect(180, 5, 201, 31))
        self.labNameCus.setText(_fromUtf8(""))
        self.labNameCus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labNameCus.setObjectName(_fromUtf8("labNameCus"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(390, 5, 111, 31))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(390, 39, 111, 31))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.labCusID = QtGui.QLabel(self.groupBox_2)
        self.labCusID.setGeometry(QtCore.QRect(180, 40, 201, 31))
        self.labCusID.setText(_fromUtf8(""))
        self.labCusID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labCusID.setObjectName(_fromUtf8("labCusID"))
        self.tableSales = QtGui.QTableWidget(sales)
        self.tableSales.setEnabled(False)
        self.tableSales.setGeometry(QtCore.QRect(10, 280, 951, 251))
        self.tableSales.setObjectName(_fromUtf8("tableSales"))
        self.tableSales.setColumnCount(5)
        self.tableSales.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableSales.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableSales.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableSales.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableSales.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableSales.setHorizontalHeaderItem(4, item)
        self.btnSelectItem = QtGui.QPushButton(sales)
        self.btnSelectItem.setGeometry(QtCore.QRect(859, 200, 101, 31))
        self.btnSelectItem.setObjectName(_fromUtf8("btnSelectItem"))
        self.btnaddItem = QtGui.QPushButton(sales)
        self.btnaddItem.setEnabled(False)
        self.btnaddItem.setGeometry(QtCore.QRect(860, 240, 101, 31))
        self.btnaddItem.setObjectName(_fromUtf8("btnaddItem"))
        self.label_18 = QtGui.QLabel(sales)
        self.label_18.setGeometry(QtCore.QRect(730, 200, 111, 31))
        self.label_18.setStyleSheet(_fromUtf8("background:#076F8A;\n"
"font-weight:bold"))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(sales)
        self.label_19.setGeometry(QtCore.QRect(619, 200, 111, 31))
        self.label_19.setStyleSheet(_fromUtf8("background:#076F8A;\n"
"font-weight:bold"))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(sales)
        self.label_20.setGeometry(QtCore.QRect(397, 200, 111, 31))
        self.label_20.setStyleSheet(_fromUtf8("background:#076F8A;\n"
"font-weight:bold"))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(sales)
        self.label_21.setGeometry(QtCore.QRect(508, 200, 111, 31))
        self.label_21.setStyleSheet(_fromUtf8("background:#076F8A;\n"
"font-weight:bold"))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(sales)
        self.label_22.setGeometry(QtCore.QRect(290, 200, 107, 31))
        self.label_22.setStyleSheet(_fromUtf8("background:#076F8A;\n"
"font-weight:bold"))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.textItemID = QtGui.QLineEdit(sales)
        self.textItemID.setEnabled(True)
        self.textItemID.setGeometry(QtCore.QRect(730, 240, 111, 31))
        self.textItemID.setAutoFillBackground(False)
        self.textItemID.setAlignment(QtCore.Qt.AlignCenter)
        self.textItemID.setReadOnly(True)
        self.textItemID.setObjectName(_fromUtf8("textItemID"))
        self.textItemName = QtGui.QLineEdit(sales)
        self.textItemName.setEnabled(True)
        self.textItemName.setGeometry(QtCore.QRect(620, 240, 111, 31))
        self.textItemName.setAutoFillBackground(False)
        self.textItemName.setAlignment(QtCore.Qt.AlignCenter)
        self.textItemName.setReadOnly(True)
        self.textItemName.setObjectName(_fromUtf8("textItemName"))
        self.textQu = QtGui.QLineEdit(sales)
        self.textQu.setEnabled(False)
        self.textQu.setGeometry(QtCore.QRect(400, 240, 111, 31))
        self.textQu.setAutoFillBackground(False)
        self.textQu.setAlignment(QtCore.Qt.AlignCenter)
        self.textQu.setObjectName(_fromUtf8("textQu"))
        self.textItemPrice = QtGui.QLineEdit(sales)
        self.textItemPrice.setEnabled(True)
        self.textItemPrice.setGeometry(QtCore.QRect(510, 240, 111, 31))
        self.textItemPrice.setAutoFillBackground(False)
        self.textItemPrice.setAlignment(QtCore.Qt.AlignCenter)
        self.textItemPrice.setReadOnly(True)
        self.textItemPrice.setObjectName(_fromUtf8("textItemPrice"))
        self.textTotalItem = QtGui.QLineEdit(sales)
        self.textTotalItem.setEnabled(True)
        self.textTotalItem.setGeometry(QtCore.QRect(290, 240, 111, 31))
        self.textTotalItem.setAutoFillBackground(False)
        self.textTotalItem.setAlignment(QtCore.Qt.AlignCenter)
        self.textTotalItem.setReadOnly(True)
        self.textTotalItem.setObjectName(_fromUtf8("textTotalItem"))
        self.label_23 = QtGui.QLabel(sales)
        self.label_23.setGeometry(QtCore.QRect(850, 540, 107, 31))
        self.label_23.setStyleSheet(_fromUtf8("color:#16a085;\n"
"font-weight:bold;"))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(sales)
        self.label_24.setGeometry(QtCore.QRect(730, 540, 107, 31))
        self.label_24.setStyleSheet(_fromUtf8("color:#16a085;\n"
"font-weight:bold;"))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(sales)
        self.label_25.setGeometry(QtCore.QRect(610, 540, 107, 31))
        self.label_25.setStyleSheet(_fromUtf8("color:#16a085;\n"
"font-weight:bold;"))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.labTotalAll = QtGui.QLabel(sales)
        self.labTotalAll.setGeometry(QtCore.QRect(490, 540, 107, 31))
        self.labTotalAll.setStyleSheet(_fromUtf8("color:#16a085;\n"
"font-weight:bold;"))
        self.labTotalAll.setAlignment(QtCore.Qt.AlignCenter)
        self.labTotalAll.setObjectName(_fromUtf8("labTotalAll"))
        self.labTimeAndDay = QtGui.QLabel(sales)
        self.labTimeAndDay.setGeometry(QtCore.QRect(30, 20, 251, 31))
        self.labTimeAndDay.setStyleSheet(_fromUtf8("color:#16a085;\n"
"font-weight:bold;"))
        self.labTimeAndDay.setAlignment(QtCore.Qt.AlignCenter)
        self.labTimeAndDay.setObjectName(_fromUtf8("labTimeAndDay"))
        self.textSearchCustomer = QtGui.QLineEdit(sales)
        self.textSearchCustomer.setEnabled(False)
        self.textSearchCustomer.setGeometry(QtCore.QRect(241, 150, 271, 31))
        self.textSearchCustomer.setAutoFillBackground(False)
        self.textSearchCustomer.setAlignment(QtCore.Qt.AlignCenter)
        self.textSearchCustomer.setObjectName(_fromUtf8("textSearchCustomer"))
        self.textSearchItem = QtGui.QLineEdit(sales)
        self.textSearchItem.setEnabled(False)
        self.textSearchItem.setGeometry(QtCore.QRect(10, 240, 271, 31))
        self.textSearchItem.setAutoFillBackground(False)
        self.textSearchItem.setAlignment(QtCore.Qt.AlignCenter)
        self.textSearchItem.setObjectName(_fromUtf8("textSearchItem"))
        self.btnDeleteItem = QtGui.QPushButton(sales)
        self.btnDeleteItem.setGeometry(QtCore.QRect(154, 200, 131, 31))
        self.btnDeleteItem.setObjectName(_fromUtf8("btnDeleteItem"))
        self.btnEditItem = QtGui.QPushButton(sales)
        self.btnEditItem.setEnabled(False)
        self.btnEditItem.setGeometry(QtCore.QRect(10, 200, 131, 31))
        self.btnEditItem.setObjectName(_fromUtf8("btnEditItem"))

        self.retranslateUi(sales)
        QtCore.QMetaObject.connectSlotsByName(sales)

    def retranslateUi(self, sales):
        sales.setWindowTitle(_translate("sales", "ادارة المبيعات", None))
        self.labAddSales.setToolTip(_translate("sales", "اظافة بيعه جديده", None))
        self.labSave.setToolTip(_translate("sales", "حفظ البيعه", None))
        self.labPrint.setToolTip(_translate("sales", "طباعة اتلفاتوره", None))
        self.labCalc.setToolTip(_translate("sales", "اله حاسبة", None))
        self.label_5.setText(_translate("sales", "اسم البائع : ", None))
        self.labNameSalse.setText(_translate("sales", "ايمن محمود محمد  عليوة ", None))
        self.label_7.setText(_translate("sales", "معرف الفاتوره :", None))
        self.labBillID.setText(_translate("sales", "SACVAJOSDV254D", None))
        self.label_9.setText(_translate("sales", "القسم :", None))
        self.labNameSection.setText(_translate("sales", "Computer", None))
        self.labSelectCus.setToolTip(_translate("sales", "اظافة عميل", None))
        self.label_15.setText(_translate("sales", "اسم  العميل  : ", None))
        self.label_16.setText(_translate("sales", "معرف العميل : ", None))
        item = self.tableSales.horizontalHeaderItem(0)
        item.setText(_translate("sales", "معرف المنتج", None))
        item = self.tableSales.horizontalHeaderItem(1)
        item.setText(_translate("sales", "اسم المنتج", None))
        item = self.tableSales.horizontalHeaderItem(2)
        item.setText(_translate("sales", "الثمن", None))
        item = self.tableSales.horizontalHeaderItem(3)
        item.setText(_translate("sales", "الكميه", None))
        item = self.tableSales.horizontalHeaderItem(4)
        item.setText(_translate("sales", "الثمن الكلي", None))
        self.btnSelectItem.setText(_translate("sales", "اختيار منتج", None))
        self.btnaddItem.setText(_translate("sales", "اظافة منتج", None))
        self.label_18.setText(_translate("sales", "معرف المنتج", None))
        self.label_19.setText(_translate("sales", "اسم المنتج ", None))
        self.label_20.setText(_translate("sales", "الكمية", None))
        self.label_21.setText(_translate("sales", "الثمن", None))
        self.label_22.setText(_translate("sales", "الثمن الكلي", None))
        self.label_23.setText(_translate("sales", "عدد المنتجات ", None))
        self.label_24.setText(_translate("sales", "0", None))
        self.label_25.setText(_translate("sales", "المبلغ الاجمالي", None))
        self.labTotalAll.setText(_translate("sales", "0", None))
        self.labTimeAndDay.setText(_translate("sales", "01-04-2017   10:21:40 PM", None))
        self.textSearchCustomer.setPlaceholderText(_translate("sales", "البحث عن الاعملاء", None))
        self.textSearchItem.setPlaceholderText(_translate("sales", "البحث عن المنتجات", None))
        self.btnDeleteItem.setText(_translate("sales", "حذف منتج ", None))
        self.btnEditItem.setText(_translate("sales", "تعديل منتج ", None))

import pathIcon_rc
