# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Settings.ui'
#
# Created: Fri Apr 14 10:48:56 2017
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName(_fromUtf8("Settings"))
        Settings.resize(938, 402)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/Settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Settings.setWindowIcon(icon)
        Settings.setLayoutDirection(QtCore.Qt.RightToLeft)
        Settings.setStyleSheet(_fromUtf8(""))
        Settings.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.SaudiArabia))
        self.groupBox = QtGui.QGroupBox(Settings)
        self.groupBox.setGeometry(QtCore.QRect(479, 20, 451, 181))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.textHostDB = QtGui.QLineEdit(self.groupBox)
        self.textHostDB.setGeometry(QtCore.QRect(12, 19, 291, 31))
        self.textHostDB.setObjectName(_fromUtf8("textHostDB"))
        self.textUserDB = QtGui.QLineEdit(self.groupBox)
        self.textUserDB.setGeometry(QtCore.QRect(12, 59, 291, 31))
        self.textUserDB.setObjectName(_fromUtf8("textUserDB"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(313, 19, 71, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(310, 59, 111, 31))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(313, 99, 91, 31))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(313, 139, 101, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.textNameDB = QtGui.QLineEdit(self.groupBox)
        self.textNameDB.setGeometry(QtCore.QRect(10, 140, 291, 31))
        self.textNameDB.setObjectName(_fromUtf8("textNameDB"))
        self.textPassDB = QtGui.QLineEdit(self.groupBox)
        self.textPassDB.setGeometry(QtCore.QRect(10, 100, 291, 31))
        self.textPassDB.setObjectName(_fromUtf8("textPassDB"))
        self.groupBox_2 = QtGui.QGroupBox(Settings)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 451, 141))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(311, 18, 71, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.textHostFTP = QtGui.QLineEdit(self.groupBox_2)
        self.textHostFTP.setGeometry(QtCore.QRect(10, 18, 291, 31))
        self.textHostFTP.setObjectName(_fromUtf8("textHostFTP"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(310, 58, 111, 31))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.textUserFTP = QtGui.QLineEdit(self.groupBox_2)
        self.textUserFTP.setGeometry(QtCore.QRect(9, 58, 291, 31))
        self.textUserFTP.setObjectName(_fromUtf8("textUserFTP"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(310, 98, 91, 31))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.textPassFTP = QtGui.QLineEdit(self.groupBox_2)
        self.textPassFTP.setGeometry(QtCore.QRect(10, 98, 291, 31))
        self.textPassFTP.setObjectName(_fromUtf8("textPassFTP"))
        self.labCheckDB = QtGui.QLabel(Settings)
        self.labCheckDB.setGeometry(QtCore.QRect(336, 270, 61, 41))
        self.labCheckDB.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.labCheckDB.setText(_fromUtf8(""))
        self.labCheckDB.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/database.png")))
        self.labCheckDB.setScaledContents(True)
        self.labCheckDB.setObjectName(_fromUtf8("labCheckDB"))
        self.labCheckFTP = QtGui.QLabel(Settings)
        self.labCheckFTP.setGeometry(QtCore.QRect(270, 270, 51, 41))
        self.labCheckFTP.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.labCheckFTP.setText(_fromUtf8(""))
        self.labCheckFTP.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/ftp.png")))
        self.labCheckFTP.setScaledContents(True)
        self.labCheckFTP.setObjectName(_fromUtf8("labCheckFTP"))
        self.groupBox_3 = QtGui.QGroupBox(Settings)
        self.groupBox_3.setGeometry(QtCore.QRect(480, 204, 451, 91))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.textEmail = QtGui.QLineEdit(self.groupBox_3)
        self.textEmail.setGeometry(QtCore.QRect(12, 9, 291, 31))
        self.textEmail.setObjectName(_fromUtf8("textEmail"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(310, 9, 121, 31))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(313, 49, 91, 31))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.textPassEmail = QtGui.QLineEdit(self.groupBox_3)
        self.textPassEmail.setGeometry(QtCore.QRect(11, 50, 291, 31))
        self.textPassEmail.setObjectName(_fromUtf8("textPassEmail"))
        self.groupBox_4 = QtGui.QGroupBox(Settings)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 170, 451, 91))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(360, 9, 71, 31))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(360, 49, 61, 31))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.comBoxCategory = QtGui.QComboBox(self.groupBox_4)
        self.comBoxCategory.setGeometry(QtCore.QRect(10, 10, 341, 31))
        self.comBoxCategory.setObjectName(_fromUtf8("comBoxCategory"))
        self.ComBoxTheme = QtGui.QComboBox(self.groupBox_4)
        self.ComBoxTheme.setGeometry(QtCore.QRect(10, 50, 341, 31))
        self.ComBoxTheme.setObjectName(_fromUtf8("ComBoxTheme"))
        self.ComBoxTheme.addItem(_fromUtf8(""))
        self.ComBoxTheme.addItem(_fromUtf8(""))
        self.btnSave = QtGui.QPushButton(Settings)
        self.btnSave.setGeometry(QtCore.QRect(130, 270, 121, 41))
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.labRunServer = QtGui.QLabel(Settings)
        self.labRunServer.setGeometry(QtCore.QRect(400, 270, 61, 41))
        self.labRunServer.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.labRunServer.setText(_fromUtf8(""))
        self.labRunServer.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/runServer.png")))
        self.labRunServer.setScaledContents(True)
        self.labRunServer.setObjectName(_fromUtf8("labRunServer"))
        self.groupBox_5 = QtGui.QGroupBox(Settings)
        self.groupBox_5.setGeometry(QtCore.QRect(480, 301, 451, 91))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.textUsername = QtGui.QLineEdit(self.groupBox_5)
        self.textUsername.setGeometry(QtCore.QRect(12, 9, 291, 31))
        self.textUsername.setPlaceholderText(_fromUtf8(""))
        self.textUsername.setObjectName(_fromUtf8("textUsername"))
        self.label_16 = QtGui.QLabel(self.groupBox_5)
        self.label_16.setGeometry(QtCore.QRect(310, 9, 121, 31))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(313, 49, 91, 31))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.textPassword = QtGui.QLineEdit(self.groupBox_5)
        self.textPassword.setGeometry(QtCore.QRect(11, 50, 291, 31))
        self.textPassword.setObjectName(_fromUtf8("textPassword"))

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(_translate("Settings", "اعدادات البرنامج", None))
        self.groupBox.setTitle(_translate("Settings", "معلومات قاعدة البينات ", None))
        self.label.setText(_translate("Settings", "المضيف :", None))
        self.label_2.setText(_translate("Settings", "اسم المستخدم :", None))
        self.label_3.setText(_translate("Settings", "كلمة المرور :", None))
        self.label_4.setText(_translate("Settings", "قاعدت البينات :", None))
        self.groupBox_2.setTitle(_translate("Settings", "FTP معلومات سيرفر ", None))
        self.label_5.setText(_translate("Settings", "المضيف :", None))
        self.label_6.setText(_translate("Settings", "اسم المستخدم :", None))
        self.label_7.setText(_translate("Settings", "كلمة المرور :", None))
        self.labCheckDB.setToolTip(_translate("Settings", "التحقق من معلومات الداتا بيس", None))
        self.labCheckFTP.setToolTip(_translate("Settings", " FTP التحقق من معلومات ", None))
        self.textEmail.setPlaceholderText(_translate("Settings", "example@gmail.com", None))
        self.label_12.setText(_translate("Settings", "البريد الالكتروني :", None))
        self.label_13.setText(_translate("Settings", "كلمة المرور :", None))
        self.label_14.setText(_translate("Settings", "القسم :", None))
        self.label_15.setText(_translate("Settings", "الثيم :", None))
        self.ComBoxTheme.setItemText(0, _translate("Settings", "الافتراضي", None))
        self.ComBoxTheme.setItemText(1, _translate("Settings", "الابيض", None))
        self.btnSave.setText(_translate("Settings", "حفظ الااعدادات ", None))
        self.labRunServer.setToolTip(_translate("Settings", "تشغيل سيرفر الدرردشه", None))
        self.label_16.setText(_translate("Settings", "اسم المستخدم :", None))
        self.label_17.setText(_translate("Settings", "كلمة المرور :", None))

import pathIcon_rc
